// src/indication/indication_config.h

#pragma once

#include "indication.h"

// ---------------------------------

#define INDICATION_STARTUP_MODE IndicationMode::BLINK
#define INDICATION_STARTUP_BLINK_COUNT 1
#define INDICATION_STARTUP_BLINK_ON_MS 100
#define INDICATION_STARTUP_BLINK_OFF_MS 0

// LED indication configuration

#define INDICATION_COMMAND_MODE IndicationMode::BLINK
#define INDICATION_COMMAND_BLINK_COUNT 1
#define INDICATION_COMMAND_BLINK_ON_MS 100
#define INDICATION_COMMAND_BLINK_OFF_MS 200

#define INDICATION_LIGHT_AUTO_MODE IndicationMode::CONTINUOUS
#define INDICATION_LIGHT_AUTO_BLINK_COUNT 0
#define INDICATION_LIGHT_AUTO_BLINK_ON_MS 0
#define INDICATION_LIGHT_AUTO_BLINK_OFF_MS 0

#define INDICATION_LIGHT_MIN_MODE IndicationMode::CONTINUOUS
#define INDICATION_LIGHT_MIN_BLINK_COUNT 0
#define INDICATION_LIGHT_MIN_BLINK_ON_MS 0
#define INDICATION_LIGHT_MIN_BLINK_OFF_MS 0

#define INDICATION_LIGHT_MAX_MODE IndicationMode::CONTINUOUS
#define INDICATION_LIGHT_MAX_BLINK_COUNT 0
#define INDICATION_LIGHT_MAX_BLINK_ON_MS 0
#define INDICATION_LIGHT_MAX_BLINK_OFF_MS 0

#define INDICATION_TEMPERATURE_MIN_MODE IndicationMode::CONTINUOUS
#define INDICATION_TEMPERATURE_MIN_BLINK_COUNT 0
#define INDICATION_TEMPERATURE_MIN_BLINK_ON_MS 0
#define INDICATION_TEMPERATURE_MIN_BLINK_OFF_MS 0

#define INDICATION_TEMPERATURE_MAX_MODE IndicationMode::CONTINUOUS
#define INDICATION_TEMPERATURE_MAX_BLINK_COUNT 0
#define INDICATION_TEMPERATURE_MAX_BLINK_ON_MS 0
#define INDICATION_TEMPERATURE_MAX_BLINK_OFF_MS 0

#define INDICATION_HUMIDITY_MIN_MODE IndicationMode::CONTINUOUS
#define INDICATION_HUMIDITY_MIN_BLINK_COUNT 0
#define INDICATION_HUMIDITY_MIN_BLINK_ON_MS 0
#define INDICATION_HUMIDITY_MIN_BLINK_OFF_MS 0

#define INDICATION_HUMIDITY_MAX_MODE IndicationMode::CONTINUOUS
#define INDICATION_HUMIDITY_MAX_BLINK_COUNT 0
#define INDICATION_HUMIDITY_MAX_BLINK_ON_MS 0
#define INDICATION_HUMIDITY_MAX_BLINK_OFF_MS 0

#define INDICATION_SILENT_MODE IndicationMode::CONTINUOUS
#define INDICATION_SILENT_BLINK_COUNT 0
#define INDICATION_SILENT_BLINK_ON_MS 200
#define INDICATION_SILENT_BLINK_OFF_MS 1000

// ---------------------------------
// Built-in LED indication

#define INDICATION_MQTT_PUBLISH_MODE IndicationMode::BLINK
#define INDICATION_MQTT_PUBLISH_BLINK_COUNT 1
#define INDICATION_MQTT_PUBLISH_BLINK_ON_MS 200
#define INDICATION_MQTT_PUBLISH_BLINK_OFF_MS 400

#define INDICATION_WIFI_CONNECTING_MODE IndicationMode::BLINK
#define INDICATION_WIFI_CONNECTING_BLINK_COUNT 5
#define INDICATION_WIFI_CONNECTING_BLINK_ON_MS 50
#define INDICATION_WIFI_CONNECTING_BLINK_OFF_MS 50
