// src/config.h

#pragma once

#define BUTTONS_READ_INTERVAL_MS 100
#define ACTIONS_MS 100
#define INDICATION_CHANGE_INTERVAL_MS 100
#define WIFI_CHECK_INTERVAL_MS 200
#define SENSOR_DHT_READ_INTERVAL_MS 2500
#define SENSOR_LDR_READ_INTERVAL_MS 2500
#define DATA_MONITOR_INTERVAL_MS 5000
#define TELEMETRY_UPDATE_INTERVAL_MS 1000
#define DATA_SEND_INTERVAL_MS 10000
#define MEMORY_CHECK_INTERVAL_MS 30000

#define LDR_ADC_PIN 33
#define LDR_BIN_PIN 32
#define DHT_PIN 13

#define BUTTON_0_PIN 5
#define BUTTON_1_PIN 18
#define BUTTON_2_PIN 19

#define LED_BUILTIN_PIN 2
#define LED_LIGHT_MANUAL_PIN 21
#define LED_LIGHT_AUTO_PIN 25
#define LED_LIGHT_MIN_PIN 23
#define LED_LIGHT_MAX_PIN 22
#define LED_TEMPERATURE_MIN_PIN 12
#define LED_TEMPERATURE_MAX_PIN 14
#define LED_HUMIDITY_MIN_PIN 27
#define LED_SERIAL_MONITOR_PIN 4
