// src/config.h

#pragma once

#include <Arduino.h>

#define BUTTONS_READ_PERIOD_MS 100
#define INDICATION_CHANGE_PERIOD_MS 100
#define SENSOR_DHT_READ_PERIOD_MS 2500
#define SENSOR_LDR_READ_PERIOD_MS 5000
#define DATA_MONITOR_PERIOD_MS 5000
#define SEND_DATA_PERIOD_MS 60000
#define MEMORY_CHECK_PERIOD_MS 60000

#define LDR_ANALOG_PIN 33
#define LDR_BINAR_PIN 32
#define DHT_PIN 13

#define BUTTON_0_PIN 5
#define BUTTON_1_PIN 18

#define LED_BUILTIN_PIN 2
#define LED_PIN 19
